language: ruby
rvm:
- 2.4.0

addons:
  postgresql: "9.6"

cache: bundler

bundler_args: "--without assets:development:production"

before_script: bundle exec rake db:create db:schema:load

script:
- bundle exec bundle audit check --update
- bundle exec rake test
# - bundle exec rubocop # TODO: make codebase rubocop compliant

notifications:
  email:
    on_success: never
    on_failure: change
