language: ruby
rvm:
- 2.3.3

addons:
  postgresql: "9.6"

cache: bundler

bundler_args: "--without assets:development:production"

before_script: bundle exec rake db:create db:schema:load

script:
- bundle audit check --update
- bundle exec rake test
# - bundle exec rubocop # TODO: make codebase rubocop compliant
