language: ruby
rvm:
- 2.5.3

addons:
  postgresql: "9.6"
  chrome: stable

cache: bundler

bundler_args: "--without assets:development:production"

before_script: bundle exec rake db:create db:schema:load

script:
- bundle exec bundle audit check --update
- bundle exec rake test
- bundle exec rspec spec
# - bundle exec rubocop # TODO: make codebase rubocop compliant

notifications:
  email:
    on_success: never
    on_failure: change
