version: '3'
# docker-compose up
services:
  db:
    image: library/postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    volumes:
      - "~/.aad/pgdata:/var/lib/postgresql/data"
      # - "~/data_cl_aad/pgdata:/var/lib/postgresql/data"

  web:
    image: citizenlabs/adopt-a-drain
    build: .
    #command: >
    #  sh -c "sleep 20 && bundle exec rails s -p 3000 -b '0.0.0.0'"
    command: >
      sh -c "
      while ! nc -z db 5432;
        do
          echo 'sleep';
          sleep 1;
        done;
      echo 'Port open!'
      bundle update;
      bundle update rake;
      bundle exec rake db:create;
      bundle exec rake db:schema:load;
      bundle exec rake db:migrate;
      bundle exec rake data:load_things;
      echo 'DONE with Data...ready to launch app';
      bundle exec rails s -p 3000 -b '0.0.0.0'
      "
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db

# Run the tests
#   docker-compose run web bundle exec rake test
